### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [weijia-cheng/frederic-mistral_mireio_harriet-waters-preston#1]
### General:

- [x] Since this is a long poem, `z3998:poem` should be applied to the `<body>` in the canto files.

- [x] Run `se clean .` to escape HTML in the long description.

- [x] There are some lint errors that still need to be addressed.

- [x] Run `se semanticate .` and commit the changes.

- [x] There are a couple instances found by `se find-mismatched-dashes .` We want to make them consistent.

### canto-2.xhtml:

- [x] The stanzas that start with "Sing, magnarello, merrily..." are parts of a song. These should be in `<blockquote>`s and their indents adjusted.

### colophon.xhtml:

- [x] The semantic for the title should be `epub:type="se:name.publication.poem"`.

**Comment by weijia-cheng** [comment]
Oops, I forgot to push the last few changes as I posted in the group! I'll take care of the others soon.
